name: Docker

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: TAG=${{ github.event.release.tag_name }} && docker buildx build --push --platform linux/amd64,linux/arm64 --tag rangeofmotion/budget:${TAG#v} -f docker/Dockerfile .
